flags: {}
extra-package-dbs: []
packages:
- .
- location: ./taffybar
  extra-dep: true
- location:
    git: git@github.com:willdonnelly/dyre.git
    commit: 11412752b483135e0c151ab90be17b217f837c4b
  extra-dep: true
- location:
    git: git@github.com:IvanMalison/gtk-traymanager.git
    commit: 517b24722b2cdab2dadbafa882ffcb6b8a1d01ff
  extra-dep: true
extra-deps:
- X11-xft-0.3.1
- dbus-0.10.13
- libxml-sax-0.7.5
- rate-limit-1.1.1
- time-units-1.0.0
- xml-helpers-1.0.0
- xmonad-contrib-0.13
resolver: lts-8.2
