flags: {}
extra-package-dbs: []
packages:
- .
- location: ./xmonad
  extra-dep: true
- location: ./xmonad-contrib
  extra-dep: true
- location: ./taffybar
  extra-dep: true
extra-deps:
- X11-xft-0.3.1
- dbus-0.10.12
- gtk-traymanager-0.1.6
- libxml-sax-0.7.5
- rate-limit-1.1.1
- time-units-1.0.0
resolver: lts-8.2
