flags: {}
extra-package-dbs: []
packages:
- '.'
- location:
    git: git@github.com:IvanMalison/xmonad-contrib.git
    commit: e4fc2341b6c5e4c27f309a371bfc140c70d813b4
- location:
    git: git@github.com:IvanMalison/taffybar.git
    commit: 39e3a95e9c2eae37ff8b67eaa31bbd18503859b1
extra-deps:
- X11-xft-0.3.1
- gtk-traymanager-0.1.6
resolver: lts-7.0
