flags: {}
extra-package-dbs: []
packages:
- '.'
- location:
    git: git@github.com:IvanMalison/xmonad.git
    commit: 10b843ad21614994b7e12fafaf300f4267aa9e40
- location:
    git: git@github.com:IvanMalison/xmonad-contrib.git
    commit: 693952e0828d9de22e5620e719905d0646a9a245
- location:
    git: git@github.com:IvanMalison/taffybar.git
    commit: 3570bdbd87a5464d7280d8750c5c153cf3dcc637
extra-deps:
- X11-xft-0.3.1
- dbus-0.10.12
- gtk-traymanager-0.1.6
- libxml-sax-0.7.5
resolver: lts-8.2
