flags: {}
extra-package-dbs: []
packages:
- '.'
- location:
    git: git@github.com:IvanMalison/xmonad.git
    commit: 751bcbbfecc2b9be9811a7147524e798c7e53bec
- location:
    git: git@github.com:IvanMalison/xmonad-contrib.git
    commit: 751bcbbfecc2b9be9811a7147524e798c7e53bec
- location:
    git: git@github.com:IvanMalison/taffybar.git
    commit: 43195e7697d5b36f861d7febeabdd340b07edb17
extra-deps:
- X11-xft-0.3.1
- gtk-traymanager-0.1.6
resolver: lts-7.0
