flags: {}
extra-package-dbs: []
packages:
- '.'
- location:
    git: git@github.com:IvanMalison/xmonad.git
    commit: 7e9c9ccb1f47c147ad19dc420361852623bd6199
- location:
    git: git@github.com:IvanMalison/xmonad-contrib.git
    commit: 4a604118dabafa04d1b3df349a0527a55808d563
- location:
    git: git@github.com:IvanMalison/taffybar.git
    commit: 43195e7697d5b36f861d7febeabdd340b07edb17
extra-deps:
- X11-xft-0.3.1
- gtk-traymanager-0.1.6
resolver: lts-7.0
